### ISSUE TITLE
Error web access to lizardfs-cgiserv

### ISSUE THREAD

**Issue by orlipr84** [lizardfs/lizardfs#907]
I just installed lizardfs-cgiserv 3.13 to monitor the service through the web page and upon entering the page it gives me the following error:

Traceback (most recent call last):
  File "/usr/sbin/lizardfs-cgiserver", line 340, in run_cgi
    exec(compile(open(self.file_name, "rb").read(), self.file_name, 'exec'), {})
  File "/usr/share/mfscgi/mfs.cgi", line 125
    raise RuntimeError, "Unknown tree to deserialize: {0}".format(tree)
                      ^
SyntaxError: invalid syntax

Any help please?

**Comment by trzysiek** [comment]
Can u tell which OS and version you are using?

**Comment by orlipr84** [comment]
I'm using for the production environment lizardfs 3.12 but i would like to test lizardfs 3.13 rc version. I installed on Ubuntu 20.04 Server following this instruction to configure the repo:

Ubuntu 20.04

apt-get update
apt-get dist-upgrade
apt-get install wget apt-transport-https
echo 'deb [trusted=yes] https://dev.lizardfs.com/packages/ focal/' | tee /etc/apt/sources.list.d/lizardfs.list
echo 'deb https://dev.lizardfs.com/packages/ focal/' | tee /etc/apt/sources.list.d/lizardfs.list
apt-get update
apt-get install lizardfs-master lizardfs-chunkserver lizardfs-client

And later installed de sofware. Sorry with my english its very bad, adn from Cuba and I use Google Translate.

Regards.
